# Generated by Django 4.2.6 on 2023-10-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lover',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
