# Generated by Django 4.2.6 on 2023-10-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lovers', '0002_alter_lover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lover',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile name'),
        ),
        migrations.AddField(
            model_name='lover',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lovers/', verbose_name='Lover image'),
        ),
    ]
